### ISSUE TITLE
Dataset 

### ISSUE THREAD

**Issue by Ashong-Nartey** [Mangodream01/ISMI_project#1]
Hello @Michellius, @Mangodream01, 

I have walked through your code on segmenting liver, liver cancer and spleen and have found it to well presented and informative. 
However, in trying to replicate the work, I have realized that, the data set is not provided neither is any link provided to the it. Could you please assist me by providing either the link to the data or the data set itself? 

Thanks and looking forward to your rapid response.

**Comment by michelbotros** [comment]
Hi @Ashong-Nartey,

We used data from the Medical Segmentation Decathlon (http://medicaldecathlon.com/). 
You can download the data there, we used the data from task 3 (Liver) and task 9 (Spleen).

Hope all is clear and goodluck!

**Comment by Ashong-Nartey** [comment]
Hello @Michellius ,
Thanks for your rapid reply and assistance. It is indeed helpful.
Cheers!
